#define USE_WEAPON_REALISM 0

#define AMMO_RELOAD_INCOMPATIBLE 1
#define AMMO_RELOAD_SOURCE_EMPTY 2
#define AMMO_RELOAD_ALREADY_FULL 4
#define AMMO_RELOAD_PARTIAL 8
#define AMMO_RELOAD_FULLY 16
#define AMMO_RELOAD_TYPE_SWAP 32
#define AMMO_RELOAD_EMPTY_MAG 64

#define AMMO_SWAP_INCOMPATIBLE 1
#define AMMO_SWAP_SOURCE_EMPTY 2
#define AMMO_SWAP_ALREADY_FULL 4
